name: Простой Action

on: [push]

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Вывести сообщение
      run: echo "Привет, GitHub Actions!"
